FROM linux AS linux-dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

COPY --from=gdb-linux /opt/gdb ${PREFIX}

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget {{GTEST_URL}} \
 && tar xvf googletest-{{GTEST_VERSION}}.tar.gz \
 && cd googletest-{{GTEST_VERSION}} \
 && cmake -B build -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${PREFIX} \
 && ninja -C build \
 && ninja -C build install \
 && rm -rf /root/* \
 ;

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget {{JSON_C_URL}} \
 && tar xvf {{JSON_C_VERSION}}.tar.gz \
 && cd json-c-{{JSON_C_VERSION}} \
 && cmake -B build -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${PREFIX} \
 && ninja -C build \
 && ninja -C build install \
 && rm -rf /root/* \
 ;

ENV LD_LIBRARY_PATH="${PREFIX}/lib"

FROM linux-dev AS linux-{{MACHINE}}-dev
