FROM darwin AS darwin-dev

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} \
    --mount=type=bind,src=osxsdk,dst=${PREFIX}/SDK cd /root \
 && cwget {{GTEST_URL}} \
 && tar xvf googletest-{{GTEST_VERSION}}.tar.gz \
 && cd googletest-{{GTEST_VERSION}} \
 && cmake -B build -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${PREFIX} \
 && ninja -C build \
 && ninja -C build install/strip \
 && mkdir -p ${PREFIX}/share/licenses/googletest/ \
 && install -m 644 LICENSE ${PREFIX}/share/licenses/googletest/ \
 && rm -rf /root/* \
 ;

FROM darwin-dev AS darwin-{{MACHINE}}-dev

LABEL org.opencontainers.image.description="Darwin dev build environment for Nickl compiler"
