FROM common AS toolchain-mingw-native

ARG PREFIX=/opt/toolchain
ARG TARGET=x86_64-w64-mingw32
ARG PATH="${PREFIX}/bin:${PATH}"

COPY --from=toolchain-mingw ${PREFIX} ${PREFIX}

RUN mkdir ${PREFIX}-native
RUN ln -s lib ${PREFIX}-native/lib64
RUN ln -s bin ${PREFIX}-native/sbin

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget {{BINUTILS_URL}} \
 && tar xvf binutils-{{BINUTILS_VERSION}}.tar.xz \
 && cd binutils-{{BINUTILS_VERSION}} \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=${TARGET} \
      --target=${TARGET} \
      --prefix=${PREFIX}-native \
      --disable-multilib \
      --disable-gprofng \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget {{GCC_URL}} \
 && tar xvf gcc-{{GCC_VERSION}}.tar.xz \
 && cd gcc-{{GCC_VERSION}} \
 && cwget {{GMP_URL}} \
 && tar xvf gmp-{{GMP_VERSION}}.tar.bz2 \
 && ln -s gmp-{{GMP_VERSION}} gmp \
 && cwget {{MPFR_URL}} \
 && tar xvf mpfr-{{MPFR_VERSION}}.tar.bz2 \
 && ln -s mpfr-{{MPFR_VERSION}} mpfr \
 && cwget {{MPC_URL}} \
 && tar xvf mpc-{{MPC_VERSION}}.tar.gz \
 && ln -s mpc-{{MPC_VERSION}} mpc \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=${TARGET} \
      --target=${TARGET} \
      --prefix=${PREFIX}-native \
      --enable-checking=release \
      --enable-languages=c,c++ \
      --disable-multilib \
      --enable-lto \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN mv ${PREFIX}-native/lib/libgcc_s_seh-1.dll ${PREFIX}-native/bin/

RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget {{MINGW_URL}} \
 && tar xvf mingw-w64-v{{MINGW_VERSION}}.tar.bz2 \
 && cd mingw-w64-v{{MINGW_VERSION}} \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=${TARGET} \
      --prefix=${PREFIX}-native/${TARGET} \
      --with-libraries=winpthreads \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN mv ${PREFIX}-native/${TARGET}/bin/libwinpthread-1.dll ${PREFIX}-native/bin/
