FROM base AS clang

COPY scripts/update-alternatives-clang.sh /root
RUN --mount=type=cache,dst=${CWGET_CACHE_DIR} cd /root \
 && cwget http://apt.llvm.org/llvm.sh \
 && chmod +x ./llvm.sh \
 && ./llvm.sh {{LLVM_VERSION}} \
 && ./update-alternatives-clang.sh {{LLVM_VERSION}} 1 \
 && rm -rf /root/* \
 ;

ENV CC=clang
ENV CXX=clang++
