FROM toolchain-mingw-common AS toolchain-mingw-native

ENV TOOLCHAIN_DIR=/opt/toolchain
ENV TOOLCHAIN_PREFIX=x86_64-w64-mingw32

COPY --from=toolchain-mingw $TOOLCHAIN_DIR $TOOLCHAIN_DIR

ENV PATH="$TOOLCHAIN_DIR/bin:$PATH"

RUN cd /root/binutils-$BINUTILS_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --target=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native \
      --disable-multilib \
      --disable-gprofng \
 && make -j \
 && make install-strip \
 && make clean \
 ;

RUN cd /root/gcc-$GCC_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --target=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native \
      --enable-checking=release \
      --enable-languages=c,c++ \
      --disable-multilib \
 && make -j \
 && make install-strip \
 && rm -rf ./* \
 ;

RUN mv $TOOLCHAIN_DIR-native/lib/libgcc_s_seh-1.dll $TOOLCHAIN_DIR-native/bin/

RUN cd /root/mingw-w64-$MINGW_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native/$TOOLCHAIN_PREFIX \
      --with-libraries=winpthreads \
 && make -j \
 && make install-strip \
 && make clean \
 ;

RUN mv $TOOLCHAIN_DIR-native/$TOOLCHAIN_PREFIX/bin/libwinpthread-1.dll $TOOLCHAIN_DIR-native/bin/
