FROM common AS toolchain-mingw-native

ENV TOOLCHAIN_DIR=/opt/toolchain
ENV TOOLCHAIN_PREFIX=x86_64-w64-mingw32

COPY --from=toolchain-mingw $TOOLCHAIN_DIR $TOOLCHAIN_DIR

ENV PATH="$TOOLCHAIN_DIR/bin:$PATH"

RUN --mount=type=cache,dst=$CWGET_CACHE_DIR cd /root \
 && cwget $BINUTILS_URL \
 && tar xvf binutils-$BINUTILS_VERSION.tar.xz \
 && cd binutils-$BINUTILS_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --target=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native \
      --disable-multilib \
      --disable-gprofng \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN --mount=type=cache,dst=$CWGET_CACHE_DIR cd /root \
 && cwget $GCC_URL \
 && tar xvf gcc-$GCC_VERSION.tar.xz \
 && cd gcc-$GCC_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --target=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native \
      --enable-checking=release \
      --enable-languages=c,c++ \
      --disable-multilib \
      --enable-lto \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN mv $TOOLCHAIN_DIR-native/lib/libgcc_s_seh-1.dll $TOOLCHAIN_DIR-native/bin/

RUN --mount=type=cache,dst=$CWGET_CACHE_DIR cd /root \
 && cwget $MINGW_URL \
 && tar xvf mingw-w64-v$MINGW_VERSION.tar.bz2 \
 && cd mingw-w64-v$MINGW_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=$TOOLCHAIN_PREFIX \
      --prefix=$TOOLCHAIN_DIR-native/$TOOLCHAIN_PREFIX \
      --with-libraries=winpthreads \
 && make -j \
 && make install-strip \
 && rm -rf /root/* \
 ;

RUN mv $TOOLCHAIN_DIR-native/$TOOLCHAIN_PREFIX/bin/libwinpthread-1.dll $TOOLCHAIN_DIR-native/bin/
