FROM linux AS linux-dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

COPY --from=gdb-linux /opt/gdb $TOOLCHAIN_DIR

ARG GTEST_VERSION=1.16.0
ARG GTEST_URL=http://github.com/google/googletest/releases/download/v$GTEST_VERSION/googletest-$GTEST_VERSION.tar.gz
RUN --mount=type=cache,dst=$CWGET_CACHE_DIR cd /root \
 && cwget $GTEST_URL \
 && tar xvf googletest-$GTEST_VERSION.tar.gz \
 && cd googletest-$GTEST_VERSION \
 && cmake -B build -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_DIR \
 && ninja -C build \
 && ninja -C build install \
 && rm -rf /root/* \
 ;

ARG JSON_C_VERSION=json-c-0.18-20240915
ARG JSON_C_URL=http://github.com/json-c/json-c/archive/refs/tags/$JSON_C_VERSION.tar.gz
RUN --mount=type=cache,dst=$CWGET_CACHE_DIR cd /root \
 && cwget $JSON_C_URL \
 && tar xvf $JSON_C_VERSION.tar.gz \
 && cd json-c-$JSON_C_VERSION \
 && cmake -B build -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_DIR \
 && ninja -C build \
 && ninja -C build install \
 && rm -rf /root/* \
 ;
