FROM toolchain-mingw-common AS toolchain-mingw-native

COPY --from=toolchain-mingw /opt/ /opt/toolchain/

ENV PATH="/opt/toolchain/bin:$PATH"

RUN cd /root/binutils-$BINUTILS_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=x86_64-w64-mingw32 \
      --target=x86_64-w64-mingw32 \
      --prefix=/opt/toolchain-native \
      --disable-multilib \
      --disable-gprofng \
 && make -j \
 && make install-strip \
 && make clean \
 ;

RUN cd /root/gcc-$GCC_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=x86_64-w64-mingw32 \
      --target=x86_64-w64-mingw32 \
      --prefix=/opt/toolchain-native \
      --enable-checking=release \
      --enable-languages=c,c++ \
      --disable-multilib \
 && make -j \
 && make install-strip \
 && rm -rf ./* \
 ;

RUN mv /opt/toolchain-native/lib/libgcc_s_seh-1.dll /opt/toolchain-native/bin/

RUN cd /root/mingw-w64-$MINGW_VERSION \
 && mkdir build \
 && cd build \
 && ../configure -v \
      --host=x86_64-w64-mingw32 \
      --prefix=/opt/toolchain-native/x86_64-w64-mingw32 \
      --with-libraries=winpthreads \
 && make -j \
 && make install-strip \
 && make clean \
 ;

RUN mv /opt/toolchain-native/x86_64-w64-mingw32/bin/libwinpthread-1.dll /opt/toolchain-native/bin/
