set(CMAKE_SYSTEM_NAME Windows)

set(PREFIX "/opt/toolchain")
set(TARGET "x86_64-w64-mingw32")

set(CMAKE_C_COMPILER "${PREFIX}/bin/${TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${PREFIX}/bin/${TARGET}-g++")
set(CMAKE_ASM_COMPILER "${PREFIX}/bin/${TARGET}-gcc")

set(CMAKE_LINKER "${PREFIX}/bin/${TARGET}-ld")
set(CMAKE_AR "${PREFIX}/bin/${TARGET}-ar")
set(CMAKE_NM "${PREFIX}/bin/${TARGET}-nm")
set(CMAKE_OBJCOPY "${PREFIX}/bin/${TARGET}-objcopy")
set(CMAKE_OBJDUMP "${PREFIX}/bin/${TARGET}-objdump")
set(CMAKE_RANLIB "${PREFIX}/bin/${TARGET}-ranlib")
set(CMAKE_STRIP "${PREFIX}/bin/${TARGET}-strip")

set(CMAKE_FIND_ROOT_PATH "${PREFIX}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR wine)
