set(CMAKE_SYSTEM_NAME Windows)

# set(TOOLCHAIN_VERSION 9.3-posix)
# set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

# set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc-posix)
# set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
# set(CMAKE_STRIP ${TOOLCHAIN_PREFIX}-strip)

# set(CMAKE_FIND_ROOT_PATH
#     /usr/${TOOLCHAIN_PREFIX}
#     /usr/lib/gcc/${TOOLCHAIN_PREFIX}/${TOOLCHAIN_VERSION}
#     /opt/mingw64
#     )

# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR wine)
