#!/bin/sh
# Cached wget

set -e

print_usage() {
  echo >&2 "Usage: $0 [-O output_file] URL"
}

OUTPUT_FILE=""
URL=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      print_usage
      exit 0
      ;;
    -O)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    *)
      if [ -n "$URL" ]; then
        print_usage
        exit 1
      fi
      URL="$1"
      shift
      ;;
  esac
done

if [ -z "$URL" ]; then
  print_usage
  exit 1
fi

if [ -z "$OUTPUT_FILE" ]; then
  OUTPUT_FILE="$(basename "$URL")"
fi

if [ -z "$CWGET_CACHE_DIR" ]; then
  CWGET_CACHE_DIR="/var/cache/cwget"
fi

mkdir -p "$CWGET_CACHE_DIR"

CACHE_FILE="$CWGET_CACHE_DIR/$OUTPUT_FILE"
TMP_FILE="$CACHE_FILE.tmp"
LOCK_FILE="$CACHE_FILE.lock"

exec 9>"$LOCK_FILE"
flock -x 9

SUCCESS=0
cleanup() {
  [ "$SUCCESS" = 0 ] && {
    rm -f "$TMP_FILE"
    rm -f "$CACHE_FILE"
  }
  exec 9>&-
  rm -f "$LOCK_FILE"
}
trap cleanup EXIT INT TERM

if [ -f "$CACHE_FILE" ]; then
  echo >&2 "Using cached file: $CACHE_FILE"
  SUCCESS=1
else
  echo >&2 "Downloading $URL"
  wget -O "$TMP_FILE" "$URL" || exit 1
  mv "$TMP_FILE" "$CACHE_FILE"
  SUCCESS=1
fi

cp "$CACHE_FILE" "$OUTPUT_FILE"
