if(DEFINED ENV{CMAKE_TOOLCHAIN_FILE})
    include($ENV{CMAKE_TOOLCHAIN_FILE})
    if(DEFINED CMAKE_SYSTEM_NAME)
        execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${CMAKE_SYSTEM_NAME}")
    endif()
else()
    execute_process(COMMAND uname -s)
endif()
