name: Nickl CI

on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop", "master"]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, mingw64]
        build_type: [debug, release]
    env:
      PLATFORM: ${{matrix.platform}}
      BUILD_TYPE: ${{matrix.build_type}}
      EXTRA_CMAKE_ARGS: -DBUILD_TESTS=ON
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./build.sh test
