name: Nickl CI

on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop", "master"]

permissions:
  contents: read

jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [linux, windows]
        build_args: [-t, -td]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh ${{ matrix.build_args }} -s ${{ matrix.system }}
      - name: Test
        run: ./build.sh ${{ matrix.build_args }} -s ${{ matrix.system }} test

  native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_args: [-nt, -ntd]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libffi-dev libgtest-dev
      - name: Build
        run: ./build.sh ${{ matrix.build_args }}
      - name: Test
        run: ./build.sh ${{ matrix.build_args }} test

  darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        build_args: [-nt, -ntd]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install googletest
      - name: Build
        run: ./build.sh ${{ matrix.build_args }}
      - name: Test
        run: ./build.sh ${{ matrix.build_args }} test
