name: Nickl CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_args: [-t, -td]
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y libffi-dev libgtest-dev llvm-15-dev zlib1g-dev
      - run: ./build.sh ${{ matrix.build_args }}
        env:
          CC: clang
          CXX: clang++
          LLVM_DIR: /usr/lib/llvm-15
      - run: ./build.sh ${{ matrix.build_args }} test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1

  darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        build_args: [-t, -td]
    steps:
      - uses: actions/checkout@v4
      - run: brew install googletest llvm
      - run: ./build.sh ${{ matrix.build_args }}
        env:
          LLVM_DIR: /opt/homebrew/opt/llvm
      - run: ./build.sh ${{ matrix.build_args }} test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1

  darwin-x86_64:
    runs-on: macos-13
    strategy:
      matrix:
        build_args: [-t, -td]
    steps:
      - uses: actions/checkout@v4
      - run: brew install googletest llvm
      - run: ./build.sh ${{ matrix.build_args }}
        env:
          LLVM_DIR: /usr/local/opt/llvm
      - run: ./build.sh ${{ matrix.build_args }} test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_args: [-t, -td]
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-diffutils
            mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-gtest
            mingw-w64-x86_64-libffi
            mingw-w64-x86_64-llvm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-winpthreads
      - shell: msys2 {0}
        run: ./build.sh ${{ matrix.build_args }}
        env:
          CC: clang
          CXX: clang++
      - shell: msys2 {0}
        run: ./build.sh ${{ matrix.build_args }} test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
